[models]
REASONING_MODEL_NAME = "qwen3-235b-a22b-thinking-2507"
INSTRUCT_MODEL_NAME = "qwen3-235b-a22b-instruct-2507"
SMALL_INSTRUCT_MODEL_NAME = "qwen3-30b-a3b-instruct-2507"
NANO_INSTRUCT_MODEL_NAME="qwen3-0.6b"